# Generated by Django 3.2.9 on 2021-11-23 08:19
"""
  Models Migrations
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
      Models Migrations
    """
    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={
                'permissions': (('can_undelete', 'Can undelete this object'),)},
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                editable=False,
                null=True),
        ),
    ]
